config/routes.rb
SWorD::Application.routes.draw do

  root :to => 'pages#home'

  match '/about', to: 'pages#about'
  match '/help', to: 'pages#help'
  match '/faq', to: 'pages#faq'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/editproject', to:'projects#edit'
  match '/crea' ,to: 'projects#new'
  match '/scopri' ,to: 'projects#index'
  match '/search_projects', to: 'projects#search_projects'

  match '/auth/:provider/callback', to: 'users#new'

  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers # ex.: get /users/1/followers
    end
    collection do
      get :search
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :projects do
    collection do
      get :search
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :contributions

  resources :backers

end

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="projects">
    <% # we need to write in this way the partial rendering for passing the collection %>
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.titolo %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago
  </span>
</li>

app/views/shared/_project_contributions_show.html.erb
<table class="table table-condensed table-bordered table-hover">
  <tr>
    <th> Quota </th>
    <th> Servizio </th>
    <th> Numero </th>
    <% if !current_user.nil? %>
        <%  if @project.data_fine > Time.now %>
            <th>  </th>
        <% end %>
    <% end %>
  </tr>



  <% @contributions.each do |contribution| %>
      <tr>
        <% if contribution.numero >=1 %>
            <%= form_for(@backer, method: 'create')  do |b| %>
                <% if !current_user.nil? %>
                    <%= b.hidden_field :user_id, value: current_user.id %>
                <% end %>
                <%= b.hidden_field :contribution_id, value: contribution.id %>
                <%= b.hidden_field :quota, value: contribution.quota %>
                <%= b.hidden_field :project_id, value: contribution.project_id %>

                <td><%= contribution.quota %></td>
                <td><%= contribution.servizio %></td>
                <td><%= contribution.numero %></td>

                <% if !current_user.nil? %>
                    <%  if @project.data_fine > Time.now %>
                        <td><%= b.submit 'Finanzia', class: 'btn btn-primary' %></td>
                    <% end %>
                <% end %>
            <% end %>
        <% end %>
      </tr>
  <% end %>
</table>

app/views/shared/_project_form.html.erb
<% @cat=["ARTE & TEMPO LIBERO","STILE DI VITA & TECNOLOGIA","SOCIAL INNOVATION","EVENTI","CIBO"] %>

<%= form_for(@project) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="row-fluid">
      <div class="span12 center">

        <div class="accordion" id="accordion2">
          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">    INFORMAZIONI GENERALI
              </a>
            </div>
            <div id="collapseOne" class="accordion-body collapse in">
              <div class="accordion-inner">
                <%= f.label :titolo %>
                <%= f.text_field :titolo, placeholder:'Inserisci un titolo di massimo 100 caratteri' %>
                <%= f.label :descrizione %>
                <%= f.text_field :descrizione, placeholder:'Descrivi il tuo progetto' %>
                <%= f.label :Budget_da_raggiungere %>
                <%= f.text_field :goal,  placeholder: 'Stabilisci il budget da raggiungere' %>
                <%= f.label :categoria %>
                <%= f.select(:categoria, @cat)%>
                <%= f.label :luogo %>
                <%= f.text_field :luogo, placeholder: 'Inserisci la città' %>
                <%= f.label :tags %>
                <%= f.text_field :tags, placeholder: 'Tag1,Tag2,Tag3' %>
              </div>
            </div>
          </div>

          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                MEDIA
              </a>
            </div>
            <div id="collapseTwo" class="accordion-body collapse">
              <div class="accordion-inner">
                <%= f.label :immagine_progetto %>
                <%= f.text_field :img_copertina, placeholder:'Inserisci l\'url dell\'immagine' %>
                <%= f.label :immagini %>
                <%= f.text_field :images, placeholder:'Inserisci le url delle immagini spaziate da una virgola' %>
                <%= f.label :video %>
                <%= f.text_field :videos, placeholder:'Inserisci l\'url del video' %>
              </div>
            </div>
          </div>

          <div class="accordion-group">
            <div class="accordion-heading">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseThree">
                COLLABORAZIONI
              </a>
            </div>
            <div id="collapseThree" class="accordion-body collapse">
              <div class="accordion-inner">
                <%= f.label :Cerco_altri_collaboratori %>
                <%= f.text_field :risorse_umane, placeholder:'Fotografo, contadino, ...' %>
                <%= f.label :'Incentiva_l\'utente più attivo' %>
                <%= f.text_field :gift, placeholder: 'Scegli un regalo per premiare l\'utente più attivo' %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <%= f.hidden_field :data_creazione %>
      <%= f.hidden_field :data_fine %>
    </div>

    <div class="row-fluid">
      <div class="span12 center">
        <% if !@project.titolo.nil?%>
            <%= f.submit 'Aggiorna il Progetto', class: 'btn btn-primary' %>
        <% else %>
            <%= f.submit 'Crea il Progetto', class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
<% end %>

app/views/shared/_project_images_show.html.erb
<% if !@project.images.nil? %>
    <% string_images = @project.images %>
    <% images = string_images.split(',')%>



    <h3>Immagini</h3>

    <div id="loading"></div>
    <canvas id="canvas_port" width="950" height="400"></canvas>
    <script>
        var j;
        j=0;
        var _nb__img;
        var _int__img = 150;
        _nb__img = 0;

        var loaded = 0;
        var async_img_load = 0;
        var _mover = 510;
        var _default_movement = 440;
        var _mouse_on = 0;
        var resources =[
        <% images.each do |img| %>
           "<%=img.gsub('"','')%>",
        <% end %>
        ]

        var img_src = [];


        jQuery.each(resources, function(index, value) {
            img_src[_nb__img] = {
                img : new Image(),
                x: Math.random() * 400 -200,
                destx: 30+ Math.random() * 70+40,
                y: 100+_int__img*_nb__img+Math.random()*100,
                yoffset: 100+Math.random()*100,
                desty: _int__img*_nb__img,
                rot: 600-Math.random() * 1200,
                destrot: 600-Math.random() * 1200,
                scale: 5,
                name: value
            }

            img_src[_nb__img].img.src = value;
            async_img_load++;

            img_src[_nb__img].img.onload = function() {
                async_img_load--;
            }

            _nb__img++;
        });

        function drawDiap(ctx,img, selected) {
            ctx.translate(-85,-40);
            var white_border = 2;
            var shadow_border = 8;
            var shadow_border_light = 10;

            //console.log('%i / %i',img.width, img.height);
            if (img.width ==0) {
                return;
            }

            var dest_height = 200;
            var dest_width = dest_height * img.width /  img.height;

            if (dest_width > dest_height) {
                dest_width = dest_height;
                dest_height = dest_width *  img.height /  img.width;
            }


            //console.log('%i / %i',img.width, img.height);
            ctx.fillStyle = 'rgba(30,30,30,0.1)';
            ctx.fillRect(0-shadow_border_light,0-shadow_border_light,dest_width+shadow_border_light*2,dest_height+shadow_border_light*2);

            if (selected) {
                ctx.fillStyle = 'rgba(30,200,30,0.5)';
                var shadow_border = 8;
                ctx.fillRect(0-shadow_border,0-shadow_border,dest_width+shadow_border*2,dest_height+shadow_border*2);
            } else {
                ctx.fillStyle = 'rgba(30,30,30,0.2)';
                ctx.fillRect(0-shadow_border,0-shadow_border,dest_width+shadow_border*2,dest_height+shadow_border*2);
            }


            ctx.fillStyle = 'rgb(255,255,255)';
            ctx.fillRect(0-white_border,0-white_border,dest_width+white_border*2,dest_height+white_border*2);

            if (img.width !=0) {
                ctx.drawImage(img,0,0,dest_width,dest_height);
            }


        }

        function drawBg(ctx) {

            var lineargradient = ctx.createLinearGradient(0, 0, 0, 400)
            lineargradient.addColorStop(0, 'rgb(240,240,240)');
            lineargradient.addColorStop(0.5, 'rgb(255,255,255)');
            lineargradient.addColorStop(0.1, 'rgb(255,255,255)');
            lineargradient.addColorStop(0.7, 'rgb(255,255,255)');
            lineargradient.addColorStop(0.99, 'rgb(230,230,230)');
            lineargradient.addColorStop(1, 'rgb(255,255,255)');
            ctx.fillStyle = lineargradient;
            ctx.fillRect(0,0,950,400);
        }

        function drawCanvas(ctx) {
            j++;
            ctx.clearRect(0, 0, 950, 400);
            //var i = j/2;
            var i = j%255;
            //console.log('%i',i);
            //ctx.restore();

            ctx.save();

            drawBg(ctx);


            jQuery.each(img_src, function(index, imag) {

                ctx.save();

                //imag.y = imag.y-1;
                var off = _mover - 425;
                imag.y = imag.y - off *48 / 950;



                if (imag.y < -250) {
                    imag.y = _nb__img * _int__img-1;
                    imag.rot = 600-Math.random() * 1200;
                    imag.destrot = 600-Math.random() * 1200;
                    imag.x = Math.random() * 400 -200;
                    imag.yoffset = 600;
                }
                if (imag.y > _nb__img * _int__img) {
                    imag.y = -250;
                    imag.rot = 600-Math.random() * 1200;
                    imag.destrot = 600-Math.random() * 1200;
                    imag.x = Math.random() * 400 -200;
                    imag.yoffset = -600;
                }


                if (imag.y < 1000) {

                    ctx.translate(imag.y+imag.yoffset,imag.x);
                    ctx.rotate(imag.rot/10000*Math.PI*2);
                    ctx.scale(imag.scale, imag.scale);
                    var selected = 0;
                    if (imag.y > _mover-60 && imag.y < _mover+60 &&_mouse_on) {
                        selected =1;
                        imag.scale = (imag.scale * 10 + 1.2) / 11
                        _selected = imag.name

                    } else {
                        imag.scale = (imag.scale * 10 + 1) / 11
                    }

                    drawDiap(ctx,imag.img,selected);

                    if (imag.y < 900) {

                        imag.x = (imag.x * 25  + imag.destx) /26;

                        imag.rot = (imag.rot * 25  + imag.destrot) /26;
                        imag.yoffset = imag.yoffset *25 / 26;
                    }

                }
                ctx.restore();
            });

            ctx.restore();

            //smooth return to "normal" slideshow
            if (!_mouse_on) {
                _mover = (_mover *10 + _default_movement) / 11
            }

        }

        function drawEvent() {
            var canvas = document.getElementById('canvas_port');
            var load_div = document.getElementById('loading');
            if (canvas.getContext){
                var ctx = canvas.getContext('2d');
                if ((async_img_load==0)) {
                    drawCanvas(ctx);
                    load_div.innerHTML = '';
                } else {
                    drawBg(ctx);
                    load_div.innerHTML = 'LOADING !';
                }
            }
        }


        $(document).ready(function(){
            $('#canvas_port').mousemove(function(e) {
                var offset = $('#canvas_port').offset();
                //console.log('move %s ', e.clientX- offset.left);

                _mover =  e.clientX- offset.left;
                _mouse_on = 1;
            });

            $('#canvas_port').mouseout(function(e) {
                //_mover = _mover /2;
                _mouse_on = 0;
            });

            $('#canvas_port').click(function(e) {
                $('#filename').html('<p>'+_selected+'</p>');
                $('#fileimg').html('<p><div style="overflow:none"><img src="'+_selected.replace('_m','')+'"/><br/><a href="'+_selected.replace('_m','_b')+'" target="blank">[Ingrandisci]</a></div></p>');
                e.stopPropagation();
            });

            _mover = _default_movement;

            setInterval('drawEvent()',60);

        });


    </script>
    <div class="row-fluid">
      <div class="span2"></div>
      <div class="span8">
        <div id="fileimg">
          <p>nessuna immagine selezionata
          </p>
        </div>
      </div>
      <div class="span2"></div>
    </div>

<% end %>

app/views/shared/_project_in_corso_slider.html.erb
<div id="myCarouseltab<%= @projectcat%>" class="carousel slide" data-interval="4000" data-pause="hover">
  <div class="carousel-inner" >
    <% if @projects_in_corso.any? %>
        <%  @projects_in_corso.each do |project|  %>


            <% if @projects_in_corso.first == project %>
                <div class="active item <%= project.id %>">
            <% else %>
                <div class="item <%= project.id %>">
            <% end %>

            <div class="carousel-cation">
              <ol class="projects">

                <div class="row-fluid" id="padre" >

                  <div class="row-fluid center" >
                    <h1><%=link_to project.titolo ,project%> </h1>
                  </div>

                  <div class="row-fluid">
                    <div class="span1"></div>
                    <div class="span6 center">
                      <% if project.img_copertina.blank?%>
                          <%=link_to image_tag("copertine_projects/ape_copertina.jpg", :size => "400x300", :class => "img-rounded"), project %>
                      <% else %>
                          <%=link_to image_tag(project.img_copertina, :size => "400x300", :class => "img-rounded"), project %>
                      <%end%>
                    </div>
                    <div class="span5" id="info">
                      <h4>
                        <% if (project.categoria=="ARTE & TEMPO LIBERO") %>
                            <span class="badge badge-success">ARTE & TEMPO LIBERO</span>
                        <% elsif (project.categoria=="STILE DI VITA & TECNOLOGIA") %>
                            <span class="badge badge-warning">STILE DI VITA & TECNOLOGIA</span>
                        <% elsif (project.categoria=="SOCIAL INNOVATION") %>
                            <span class="badge badge-important">SOCIAL INNOVATION</span>
                        <% elsif (project.categoria=="EVENTI") %>
                            <span class="badge badge-info">EVENTI</span>
                        <% elsif (project.categoria=="CIBO") %>
                            <span class="badge badge" style="background-color:#136ba5">CIBO</span>
                        <% end %>
                      </h4>


                      <div class="row-fluid">
                        <h4>
                          <% if !project.user.sesso.nil? %>
                              <% if project.user.sesso == "M" %>
                                  <%= image_tag("icone/man-user.png", :size => "25x25") %>
                              <% else %>
                                  <%= image_tag("icone/woman-user.png", :size => "25x25") %>
                              <% end %>
                          <% else %>
                              <%= image_tag("icone/user.png", :size => "25X25") %>
                          <% end %>
                          <% if signed_in? %>
                              <%= link_to project.user.name, project.user %>
                          <% else %>
                              <%= project.user.name %>
                          <% end %>
                        </h4>
                        <h4>
                          <%= image_tag("icone/pushpin.png", :size => "25x25") %>

                          <%= project.luogo %>
                        </h4>
                      </div>

                      <div class="row-fluid">
                        <div class="span12">
                          <h5>Di cosa si tratta?  </h5>
                          <p><%= project.descrizione %>   </p>
                        </div>
                      </div>
                    </div>



                  </div>

                  <div class="row-fluid" >

                    <div class="span1"></div>
                    <div class="span7">
                      <div class="progress progress-success progress-striped active">
                            <div class="bar" style="width: 100%;"></div>
                      </div>
                    </div>
                    <div class="span4">
                      <h5> Budget attuale: <%= project.budget_attuale %> € <%= image_tag("icone/finanziatori.png", :size => "32x32") %></h5>
                      <h5> <%= image_tag("icone/champion-cup.png", :size => "25x25") %> Goal <%= project.goal %> € </h5>
                    </div>
                  </div>

                  <div class="row-fluid">
                    <div class="span1"></div>
                    <div class="span7">

                      <% dif = distance_of_time_in_words(Time.now, project.data_fine, include_seconds = true) %>
                      <% dif.to_s
                         if dif.include? 'day'
                           dif.sub!('day','giorno')
                         end
                         if dif.include? 'giornos'
                           dif.sub!('giornos','giorni')
                         end
                         if dif.include? 'about'
                           dif.sub!('about','circa')
                         end
                         if dif.include? 'hour'
                           dif.sub!('hour','ora')
                         end
                         if dif.include? 'oras'
                           dif.sub!('oras','ore')
                         end
                         if dif.include? 'less than a minute'
                           dif.sub!('less than a minute','meno di un minuto')
                         end
                         if dif.include? 'less than'
                           dif.sub!('less than','meno di')
                         end
                         if dif.include? 'minute'
                           dif.sub!('minute','minuto')
                         end
                         if dif.include? 'minutos'
                           dif.sub!('minutos','minuti')
                         end
                         if dif.include? 'year'
                           dif.sub!('year','anno')
                         end
                         if dif.include? 'annos'
                           dif.sub!('annos','anni')
                         end
                         if dif.include? 'month'
                           dif.sub!('month','mese')
                         end
                         if dif.include? 'meses'
                           dif.sub!('meses','mesi')
                         end
                         if dif.include? 'half a'
                           dif.sub!('half a','mezzo')
                         end%>

                      <% ore_rimanenti = ((project.data_fine- Time.zone.now)/1.hours).to_i %>
                      <div class="progress progress-danger progress-striped active">
                        <div class="bar" style="width: <%= 100-ore_rimanenti * 100 / 672 %>%;"></div>
                      </div>
                    </div>

                    <div class="span4">
                      <h5>  <%= image_tag("icone/clock.png", :size => "25x25") %>
                        Hai ancora: <%= dif %> </h5>
                    </div>
                  </div>
                </div>
              </ol>
            </div>
            </div>

        <% end %>
    <% end %>
    </div>
    <a class="carousel-control left" href="#myCarouseltab<%=@projectcat%>" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarouseltab<%=@projectcat%>" data-slide="next">&rsaquo;</a>

  </div>
</div>

app/views/shared/_stats.html.erb
<% # we are going to use this partial in the home and in the user profile;
   # in the home @user is nil and needs to be filled %>
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followed_users.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
     followers
  </a>
</div>

app/views/shared/_user_dna.html.erb
  <% @numberCAT1 %>
  <% @numberCAT2 %>
  <% @numberCAT3 %>
  <% @numberCAT4 %>
  <% @numberCAT5 %>
  <div class="progress">
    <% if (@numTotCats!=0) %>
        <div class="bar bar-success" style="width: <%= @numberCAT1*100/@numTotCats%>%;"></div>
        <div class="bar bar-warning" style="width:<%= @numberCAT2*100/@numTotCats%>% ;"></div>
        <div class="bar bar-danger" style="width: <%= @numberCAT3*100/@numTotCats%>%;"></div>
        <div class="bar bar-info" style="width: <%= @numberCAT4*100/@numTotCats%>%;"></div>
        <div class="bar bar" style="width: <%= @numberCAT5*100/@numTotCats%>%;"></div>
    <% else %>
           <div class="bar bar-action" style="width: 0%"></div>
          <p style="font-size: 11px"> Crea progetti per colorare il tuo DNA</p>
    <% end %>
  </div>

app/views/shared/_user_projectprogress_slider.html.erb
<% if @projects_progress.any? %>
    <div id="myCarouseltab<%= @projectcat%>" class="carousel slide" data-interval="4000" data-pause="hover">
      <div class="carousel-inner" >

        <%  @projects_progress.each do |project|  %>
            <% if @projects_progress.first == project %>
                <div class="active item <%= project.id %>">
            <% else %>
                <div class="item <%= project.id %>">
            <% end %>

            <div class="carousel-cation">
              <ol class="projects">

                <div class="row-fluid" id="padre" >

                  <div class="row-fluid center" >
                    <h1><%=link_to project.titolo ,project%> </h1>
                  </div>

                  <div class="row-fluid">
                    <div class="span1"></div>
                    <div class="span6 center">
                      <% if project.img_copertina.blank?%>
                          <%=link_to image_tag("copertine_projects/ape_copertina.jpg", :size => "400x300" , :class => "img-rounded"), project %>
                      <% else %>
                          <%=link_to image_tag(project.img_copertina, :size => "400x300", :class => "img-rounded"), project %>
                      <%end%>
                    </div>

                    <div class="span5" id="info">
                      <h4>
                        <% if (project.categoria=="ARTE & TEMPO LIBERO") %>
                            <span class="badge badge-success">ARTE & TEMPO LIBERO</span>
                        <% elsif (project.categoria=="STILE DI VITA & TECNOLOGIA") %>
                            <span class="badge badge-warning">STILE DI VITA & TECNOLOGIA</span>
                        <% elsif (project.categoria=="SOCIAL INNOVATION") %>
                            <span class="badge badge-important">SOCIAL INNOVATION</span>
                        <% elsif (project.categoria=="EVENTI") %>
                            <span class="badge badge-info">EVENTI</span>
                        <% elsif (project.categoria=="CIBO") %>
                            <span class="badge badge" style="background-color:#136ba5">CIBO</span>
                        <% end %>
                      </h4>


                      <div class="row-fluid">
                        <h4>
                          <% if !project.user.sesso.nil? %>
                              <% if project.user.sesso == "M" %>
                                  <%= image_tag("icone/man-user.png", :size => "25x25") %>
                              <% else %>
                                  <%= image_tag("icone/woman-user.png", :size => "25x25") %>
                              <% end %>
                          <% else %>
                              <%= image_tag("icone/user.png", :size => "25X25") %>
                          <% end %>
                          <% if signed_in? %>
                              <%= link_to project.user.name, project.user %>
                          <% else %>
                              <%= project.user.name %>
                          <% end %>
                        </h4>
                        <h4>
                          <%= image_tag("icone/pushpin.png", :size => "25x25") %>

                          <%= project.luogo %>
                        </h4>
                      </div>

                      <div class="row-fluid">
                        <div class="span12">
                          <h5>Di cosa si tratta?  </h5>
                          <p><%= project.descrizione %>   </p>
                        </div>
                      </div>
                    </div>



                  </div>



                  <div class="row-fluid" >

                    <div class="span1"></div>
                    <div class="span7">
                      <div class="progress progress-success progress-striped active">
                        <%if (project.budget_attuale * 100 / project.goal > 100) %>
                            <div class="bar" style="width: 100%;"></div>
                        <% else %>
                            <div class="bar" style="width: <%= project.budget_attuale * 100 / project.goal %>%;"></div>
                        <% end %>
                      </div>
                    </div>
                    <div class="span4">
                      <h5> Budget attuale: <%= project.budget_attuale %> € <%= image_tag("icone/finanziatori.png", :size => "32x32") %></h5>
                      <h5> <%= image_tag("icone/champion-cup.png", :size => "25x25") %> Goal <%= project.goal %> € </h5>
                    </div>
                  </div>

                  <div class="row-fluid">
                    <div class="span1"></div>
                    <div class="span7">

                      <% dif = distance_of_time_in_words(Time.now, project.data_fine, include_seconds = true) %>
                      <% dif.to_s
                         if dif.include? 'day'
                           dif.sub!('day','giorno')
                         end
                         if dif.include? 'giornos'
                           dif.sub!('giornos','giorni')
                         end
                         if dif.include? 'about'
                           dif.sub!('about','circa')
                         end
                         if dif.include? 'hour'
                           dif.sub!('hour','ora')
                         end
                         if dif.include? 'oras'
                           dif.sub!('oras','ore')
                         end
                         if dif.include? 'less than a minute'
                           dif.sub!('less than a minute','meno di un minuto')
                         end
                         if dif.include? 'less than'
                           dif.sub!('less than','meno di')
                         end
                         if dif.include? 'minute'
                           dif.sub!('minute','minuto')
                         end
                         if dif.include? 'minutos'
                           dif.sub!('minutos','minuti')
                         end
                         if dif.include? 'year'
                           dif.sub!('year','anno')
                         end
                         if dif.include? 'annos'
                           dif.sub!('annos','anni')
                         end
                         if dif.include? 'month'
                           dif.sub!('month','mese')
                         end
                         if dif.include? 'meses'
                           dif.sub!('meses','mesi')
                         end
                         if dif.include? 'half a'
                           dif.sub!('half a','mezzo')
                         end%>

                      <% ore_rimanenti = ((project.data_fine- Time.zone.now)/1.hours).to_i %>
                      <div class="progress progress-danger progress-striped active">
                        <div class="bar" style="width: <%= 100-ore_rimanenti * 100 / 672 %>%;"></div>
                      </div>
                    </div>

                    <div class="span4">
                      <h5>  <%= image_tag("icone/clock.png", :size => "25x25") %>
                        Hai ancora: <%= dif %> </h5>
                    </div>
                  </div>
                </div>
              </ol>

            </div>
            </div>
        <% end %>
        </div>
        <a class="carousel-control left" href="#myCarouseltab<%=@projectcat%>" data-slide="prev">&lsaquo;</a>
        <a class="carousel-control right" href="#myCarouseltab<%=@projectcat%>" data-slide="next">&rsaquo;</a>


      </div>
<% else %>
    <div class="row-fluid center">
      <div class="span12">
        <h3>Non hai progetti in corso</h3>
        <h3><%= link_to "Crea ora il tuo nuovo progetto", crea_path %> </h3>
      </div>
    </div>
<% end %>