config/routes.rb
SWorD::Application.routes.draw do

  root :to => 'pages#home'

  match '/about', to: 'pages#about'
  match '/help', to: 'pages#help'
  match '/faq', to: 'pages#faq'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/editproject', to:'projects#edit'
  match '/crea' ,to: 'projects#new'
  match '/scopri' ,to: 'projects#index'
  match '/search_projects', to: 'projects#search_projects'

  match '/auth/:provider/callback', to: 'users#new'

  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers # ex.: get /users/1/followers
    end
    collection do
      get :search
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :projects do
    collection do
      get :search
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :contributions

  resources :backers

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#t.integer  "user_id"
#t.datetime "created_at",     :null => false
#t.datetime "updated_at",     :null => false
#t.string   "titolo"
#t.string   "descrizione"
#t.string   "categoria"
#t.datetime "data_creazione"
#t.datetime "data_fine"
#t.string   "tags"
#t.string   "images"
#t.string   "videos"
#t.float    "budget_attuale"
#t.float    "goal"
#t.string   "img_copertina"
#t.string   "risorse_umane"
#t.string   "gift"
#

class Project < ActiveRecord::Base
  # only content must be accessible, in order to avoid manual (and wrong) associations between posts and users
  attr_accessible :titolo, :descrizione, :categoria, :data_creazione, :data_fine,:tags, :images, :videos, :budget_attuale, :goal, :img_copertina, :risorse_umane, :gift ,:luogo

  has_many :contributions, dependent: :destroy

  # each projects belong to a specific user
  belongs_to :user

  # descending order for getting the projects
  default_scope order: 'projects.created_at DESC'

  # user_id must be present while creating a new project...

  validates :user_id, presence: true

  # titolo must be present and not longer than 100 chars
  validates :titolo, presence: true, length: {maximum: 100}

  validates :descrizione, :categoria, :data_creazione, :data_fine,:tags, :goal,:luogo, presence: true

  # get user's projects plus all the projects written by her followed users
  def self.from_users_followed_by(user)
    followed_user_ids = 'SELECT followed_id FROM relationships WHERE follower_id = :user_id'
    where("user_id IN (#{followed_user_ids}) OR user_id = :user_id", user_id: user.id)
  end

  def self.search(search)
    if search
      where('titolo LIKE ? or categoria LIKE ? or luogo LIKE ? or tags LIKE ?', "%#{search}%","%#{search}%","%#{search}%","%#{search}%")
    else
      scoped # return an empty result set
    end
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # check if the user is logged in (e.g., for editing only his information)
  before_filter :signed_in_user, only: [:edit, :update, :index, :destroy, :show]
  # check if the current user is the correct user (e.g., for editing only his information)
  before_filter :correct_user, only: [:edit, :update, :destroy]


  def new
    @project = Project.new(data_creazione: Time.now, data_fine: Time.now + 4.weeks)
    @user=current_user
    @numberCAT1= findNumberCAT1
    @numberCAT2= findNumberCAT2
    @numberCAT3= findNumberCAT3
    @numberCAT4= findNumberCAT4
    @numberCAT5= findNumberCAT5
    @numTotCats=@numberCAT1+@numberCAT2+@numberCAT3+@numberCAT4+@numberCAT5

  end

  def show
    @backer_numbers = count_backer(params[:id])
    @project = Project.find(params[:id])
    @contributions = @project.contributions
    @backer = Backer.new
    @username = @project.user.name
    @user = @project.user


  end

  def index
    @projects_friends = findProjects_Friends if signed_in?
    @projects_recently = findProjects_recently
    @projects_complete = findProjects_complete
    @projects_in_corso = findProjects_in_corso
    @user = current_user
    @projects = Project.paginate(page: params[:page], per_page: 10)
    @numberCAT1= findNumberCAT1
    @numberCAT2= findNumberCAT2
    @numberCAT3= findNumberCAT3
    @numberCAT4= findNumberCAT4
    @numberCAT5= findNumberCAT5
    @numTotCats=@numberCAT1+@numberCAT2+@numberCAT3+@numberCAT4+@numberCAT5

  end

  def create
    # build a new project from the information contained in the "new project" form
    @project = current_user.projects.new(params[:project])
    @project.budget_attuale=0
    @project.save

    if @project.save
      flash[:success] = 'Progetto Creato!'
      redirect_to @project
    else
      flash[:error] = 'Progetto non Creato!'
      redirect_to '/crea'
    end
  end

  def edit
    # intentionally left empty since the correct_user method (called by before_filter) initialize the @user object
    # without the correct_user method, this action should contain:
    # @user = User.find(params[:id])
  end

  def update

    @id_project= @project.id

    if @project.update_attributes(params[:project])
      # handle a successful update
      flash[:success] = 'Project aggiornato'

      # go to the project
      redirect_to @project
    else
      # handle a failed update
      render 'edit'
    end
  end

  def destroy
    @project.destroy
    redirect_to current_user
  end

  def search_projects
    @projects = Project.search(params[:search]).paginate(page: params[:page])
  end

  def count_backer(id)
    Backer.count_by_sql(["SELECT COUNT(DISTINCT user_id) FROM backers b, contributions c WHERE b.contribution_id = c.id AND c.project_id = ?",id])
  end

  private

  def correct_user
    # does the user have a post with the given id?
    @project = current_user.projects.find_by_id(params[:id])
    # if not, redirect to the home page
    redirect_to root_url if @project.nil?
  end

  def findProjects_complete

    Project.find_by_sql("SELECT * FROM projects WHERE data_fine < current_timestamp AND budget_attuale > goal ORDER BY data_fine DESC")

  end

  def findProjects_in_corso

    Project.find_by_sql("SELECT * FROM projects WHERE data_fine > current_timestamp AND budget_attuale > goal ORDER BY data_creazione")

  end

  def findProjects_recently

    Project.find_by_sql("SELECT * FROM projects WHERE data_fine >= current_timestamp AND budget_attuale < goal ORDER BY data_creazione DESC LIMIT 10")

  end

  def findProjects_Friends

    Project.find_by_sql(["SELECT * FROM projects WHERE data_fine > current_timestamp AND user_id IN(SELECT followed_id FROM relationships WHERE follower_id = ?) ORDER BY data_fine",current_user.id])

  end

  def findNumberCAT1

    Project.count_by_sql(["SELECT COUNT (id) FROM projects WHERE user_id = ? AND categoria='ARTE & TEMPO LIBERO' ", @user.id])

  end

  def findNumberCAT2

    Project.count_by_sql(["SELECT COUNT (id) FROM projects WHERE user_id = ? AND categoria='STILE DI VITA & TECNOLOGIA' ", @user.id])

  end

  def findNumberCAT3

    Project.count_by_sql(["SELECT COUNT (id) FROM projects WHERE user_id = ? AND categoria='SOCIAL INNOVATION' ", @user.id])

  end

  def findNumberCAT4

    Project.count_by_sql(["SELECT COUNT (id) FROM projects WHERE user_id = ? AND categoria='EVENTI' ", @user.id])

  end

  def findNumberCAT5

    Project.count_by_sql(["SELECT COUNT (id) FROM projects WHERE user_id = ? AND categoria='CIBO' ", @user.id])

  end



end

app/views/projects/_project.html.erb
<li>
  <div class="row-fluid"><h2><%= project.titolo %></h2></div>
  <div class="row-fluid"><h4><%= project.luogo %></h4></div>
   <div class="row-fluid">
     <div class="span6">
  <% unless project.img_copertina.blank? %>
      <%= image_tag(project.img_copertina , :height => '200px', :width => '300px')%>
  <%else%>
      <%= image_tag("copertine_projects/ape_copertina.jpg" , :height => '200px', :width => '300px')%>
  <% end %>
     </div>
     <div class="span6">
      <h5> <%= project.descrizione %>   </h5>
     </div>
   </div>

  <span class="timestamp">
   <% dif = time_ago_in_words(project.created_at, include_seconds = true) %>
    <% dif.to_s
       if dif.include? 'day'
         dif.sub!('day','giorno')
       end
       if dif.include? 'giornos'
         dif.sub!('giornos','giorni')
       end
       if dif.include? 'about'
         dif.sub!('about','circa')
       end
       if dif.include? 'hour'
         dif.sub!('hour','ora')
       end
       if dif.include? 'oras'
         dif.sub!('oras','ore')
       end
       if dif.include? 'less than a minute'
         dif.sub!('less than a minute','meno di un minuto')
       end
       if dif.include? 'less than'
         dif.sub!('less than','meno di')
       end
       if dif.include? 'minute'
         dif.sub!('minute','minuto')
       end
       if dif.include? 'minutos'
         dif.sub!('minutos','minuti')
       end
       if dif.include? 'year'
         dif.sub!('year','anno')
       end
       if dif.include? 'annos'
         dif.sub!('annos','anni')
       end
       if dif.include? 'month'
         dif.sub!('month','mese')
       end
       if dif.include? 'meses'
         dif.sub!('meses','mesi')
       end
       if dif.include? 'half a'
         dif.sub!('half a','mezzo')
       end%>
    Creato <%= dif %> fa
  </span>
  <div class="row-fluid">
  <%= link_to 'Visualizza', project, class: 'btn btn-large btn-info'%>
  <% if current_user?(project.user) %>
      <%= link_to 'Elimina', project, method: :delete, data: { confirm: 'Are you sure?' }, title: project.titolo, class: 'btn btn-large btn-danger'%>
  <% end %>
  </div>
</li>

app/views/projects/_search_projects_form.html.erb
<% # form_tag is equivalent to form_for, but it is used for generic form, without a model behind
    # a search form always uses a GET method %>
<%= form_tag search_projects_path, method: 'get', class: 'navbar' do %>
    <% # text_field_tag: the first parameter is the id/name of the input tag; the second is the value of the tag %>
    <%= text_field_tag :search, params[:search], class: 'search-query', placeholder: 'Cerca' %>
<% end %>

app/views/projects/edit.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'Update Project' %>

<h1>Aggiorna il tuo progetto</h1>

<%= render 'shared/project_form' %>

app/views/projects/index.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'Scopri i Progetti' %>
<div class="container-fluid">
  <div class="row-fluid">

    <aside class="span3">
      <%= render 'shared/user_info' %>
      <%= link_to 'Il mio profilo', current_user, class: 'btn btn-medium btn-info'%>
      <%= render 'shared/stats' %>
    </aside>

      <div class="span6 center">
        <%= image_tag ("icone/binoculars.png") %>
        <h1>Scopri nuovi Progetti</h1>
        <h3>Cerca i progetti </h3>
        <h5>in base al luogo, categoria, tag o al titolo del progetto</h5>
        <%= render 'projects/search_projects_form' %>
      </div>

</div>

    <div class="row-fluid">
      <div class="span10 offset1">
        <h2><%= image_tag("icone/champion-cup.png")%> Progetti terminati con successo   </h2>
        
        <% @projectcat = 1 %>
        <% @projects_complete  %>
        <%= render 'shared/project_complete_slider' %>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span10 offset1">
        <h2><%= image_tag("icone/star.png", :size => "50x50")%> Progetti più popolari  </h2>
        <% @projectcat = 2 %>
        <% @projects_in_corso  %>
        <%= render 'shared/project_in_corso_slider' %>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span10 offset1">
        <h2> <%= image_tag("icone/cronometer.png")%> Ultimi progetti creati </h2>
        <% @projectcat = 3 %>
        <% @projects_recently  %>
        <%= render 'shared/project_recently_slider' %>
      </div>
    </div>


  <div class="row-fluid">
    <div class="span10 offset1">
      <h2> <%= image_tag("icone/amici.jpg", :size => "60x60")%> Progetti degli amici </h2>
      <% @projectcat = 4 %>
      <% @projects_friends  %>
      <% if signed_in? %>
          <% if !current_user.followers.nil? %>
              <%= render 'shared/project_friends_slider' %>
          <% end %>
      <% end %>
    </div>
  </div>


</div>

app/views/projects/new.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'Crea un nuovo progetto' %>
<div class="container-fluid">
  <div class="row-fluid">
    <aside class="span3">
      <%= render 'shared/user_info' %>
      <%= link_to 'Il mio profilo', current_user, class: 'btn btn-medium btn-info'%>
      <%= render 'shared/stats' %>
    </aside>

      <div class="span6 center">
        <%= image_tag("icone/bulb.png")%>
        <h1>Crea il tuo progetto</h1>
        <p>  <%= render 'shared/project_form' %>     </p>
      </div>



  </div>
</div>

app/views/projects/search_projects.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, 'Risultati ricerca' %>


<div class="row-fluid">
  <h1>Risultati della ricerca</h1>
  <div class="span6 center offset3">

    <h3>Cerca i progetti</h3>
    <h5>in base al luogo, alla categoria,tag o al titolo del progetto</h5>
    <%= render 'projects/search_projects_form' %>
  </div>
</div>
<div class="row-fluid">
  <div class="span8 center offset2">
<%= will_paginate %>

<ul class="projects">
  <%= render @projects %>
</ul>

<%= will_paginate %>


<%=  link_to 'Torna indietro', projects_path  %>

  </div>
</div>

app/views/projects/show.html.erb
<% #Provide the page title in a symbol to application.html.erb to avoid duplication %>
<% provide :title, @project.titolo %>

<div class="container-fluid">
<div class="row-fluid center">

  <% unless @project.img_copertina.blank? %>
      <%= image_tag(@project.img_copertina , :height => '100%', :width => '100%', :class => "img-rounded", :id => "copertina")%>
  <%else%>
      <%= image_tag('copertine_projects/ape_copertina.jpg' , :height => '100%', :width => '100%', :class => "img-rounded", :id => "copertina")%>

  <% end %>

  <h1>
    <%= @project.titolo %>
  </h1>

</div>


<div class="row-fluid">

<div class="span2"></div>
<div class="span6">
  <%if (@project.data_fine < Time.zone.now) %>
      <div class="progress progress-success progress">
  <% else %>
      <div class="progress progress-success progress-striped active">
  <% end %>
  <%if (@project.budget_attuale * 100 / @project.goal > 100) %>
      <div class="bar" style="width: 100%;"></div>
  <% else %>
      <div class="bar" style="width: <%= @project.budget_attuale * 100 / @project.goal %>%;"></div>
  <% end %>
  </div>
  </div>
  <div class="span3">
    <h5> Budget attuale: <%= @project.budget_attuale %> € <%= image_tag("icone/finanziatori.png", :size => "32x32") %></h5>
    <h5> <%= image_tag("icone/champion-cup.png", :size => "25x25") %> Goal <%= @project.goal %> € </h5>
  </div>
</div>

<div class="row-fluid">
  <div class="span2"></div>

  <%if (@project.data_fine < Time.zone.now) %>
      <div class="span6">
        <div class="progress progress-danger progress">
          <div class="bar" style="width: 100%;"></div>
        </div>
      </div>
      <div class="span3">
        <h5>  <%= image_tag("icone/clock.png", :size => "25x25") %>
          Completato! </h5>
      </div>
  <% else %>
      <div class="span6">
        <% dif = distance_of_time_in_words(Time.now, @project.data_fine, include_seconds = true) %>
        <% dif.to_s
           if dif.include? 'day'
             dif.sub!('day','giorno')
           end
           if dif.include? 'giornos'
             dif.sub!('giornos','giorni')
           end
           if dif.include? 'about'
             dif.sub!('about','circa')
           end
           if dif.include? 'hour'
             dif.sub!('hour','ora')
           end
           if dif.include? 'oras'
             dif.sub!('oras','ore')
           end
           if dif.include? 'less than a minute'
             dif.sub!('less than a minute','meno di un minuto')
           end
           if dif.include? 'less than'
             dif.sub!('less than','meno di')
           end
           if dif.include? 'minute'
             dif.sub!('minute','minuto')
           end
           if dif.include? 'minutos'
             dif.sub!('minutos','minuti')
           end
           if dif.include? 'year'
             dif.sub!('year','anno')
           end
           if dif.include? 'annos'
             dif.sub!('annos','anni')
           end
           if dif.include? 'month'
             dif.sub!('month','mese')
           end
           if dif.include? 'meses'
             dif.sub!('meses','mesi')
           end
           if dif.include? 'half a'
             dif.sub!('half a','mezzo')
           end%>

        <% ore_rimanenti = ((@project.data_fine- Time.zone.now)/1.hours).to_i %>
        <div class="progress progress-danger progress-striped active">
          <div class="bar" style="width: <%= 100-ore_rimanenti * 100 / 672 %>%;"></div>
        </div>
      </div>

      <div class="span3">
        <h5>  <%= image_tag("icone/clock.png", :size => "25x25") %>
          Hai ancora: <%= dif %> </h5>
      </div>
  <% end %>
</div>




<div class="row-fluid">
  <div class="span8 offset2">

    <div class="span6">
      <% p_url = "http://www.facebook.com/sharer.php?u=".concat request.url %>
      <%=link_to image_tag("icone/share.png", :size => "30x30"),p_url %>

      <h4>
        <%= image_tag("icone/tag.png", :size => "25x25") %>
        <% if (@project.categoria=="ARTE & TEMPO LIBERO") %>
            <span class="badge badge-success">ARTE & TEMPO LIBERO</span>
        <% elsif (@project.categoria=="STILE DI VITA & TECNOLOGIA") %>
            <span class="badge badge-warning">STILE DI VITA & TECNOLOGIA</span>
        <% elsif (@project.categoria=="SOCIAL INNOVATION") %>
            <span class="badge badge-important">SOCIAL INNOVATION</span>
        <% elsif (@project.categoria=="EVENTI") %>
            <span class="badge badge-info">EVENTI</span>
        <% elsif (@project.categoria=="CIBO") %>
            <span class="badge badge" style="background-color:#136ba5">CIBO</span>
        <% end %>
      </h4>

      <h4>
        <%= image_tag("icone/pushpin.png", :size => "25x25") %>
        <%= @project.luogo %>
      </h4>

      <h4>
        <% if !@project.user.sesso.nil? %>
            <% if @project.user.sesso == "M" %>
                <%= image_tag("icone/man-user.png", :size => "25x25") %>
            <% else %>
                <%= image_tag("icone/woman-user.png", :size => "25x25") %>
            <% end %>
        <% else %>
            <%= image_tag("icone/user.png", :size => "25x25") %>
        <% end %>
        <%=link_to @username, @user %>
      </h4>
      <h4>
        <%= image_tag("icone/finanziatori.png", :size => "32x32") %>
        backers <%= @backer_numbers %>
      </h4>
      <br>
      <br>
      <br>
      <br>
      <h2>Descrizione</h2>
      <p>
        <%= @project.descrizione %>
      </p>
      <br>
      <br>
      <h4>Tags</h4>
      <p>
        <%= @project.tags %>
      </p>
      <% if !current_user.nil? %>
          <% if current_user.id == @project.user.id %>
              <%= link_to "Modifica il tuo Progetto", edit_project_path , class: 'btn btn-medium btn-warning'%>
          <% end %>
      <% end %>




    </div>
    <div class="span6 ">

      <h4>Contributi: </h4>

      <%= render 'shared/project_contributions_show' %>

      <% if !current_user.nil? %>
          <% if current_user.id == @project.user.id %>
              <%= link_to "Modifica/Aggiorna i Contributi", contributions_path(project_id: @project.id), class: 'btn btn-medium, btn-warning'%>
          <% end %>
      <% end %>

      <br>
      <br>
      <br>
      <% if !@project.risorse_umane.nil? %>
          <h4>Collaboratori</h4>
          <p>
            <%= @project.risorse_umane %>
          </p>
      <% end %>


    </div>

  </div>

  <div class="row-fluid">
    <div class="span12 center">
      <section>

      </section>
    </div>
  </div>
  <div class="row-fluid">

    <div class="span12 center">
      <section>
        <%= render 'shared/project_images_show' %>
      </section>

    </div>

  </div>
  <div class="row-fluid">
    <div class="span2 center">
    </div>
    <div class="span8 center">
      <section>
        <%= render 'shared/project_videos_show' %>
      </section>
    </div>
    <div class="span2 center">
    </div>
  </div>

</div>

</div>
</div>