config/routes.rb
SWorD::Application.routes.draw do

  root :to => 'pages#home'

  match '/about', to: 'pages#about'
  match '/help', to: 'pages#help'
  match '/faq', to: 'pages#faq'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/editproject', to:'projects#edit'
  match '/crea' ,to: 'projects#new'
  match '/scopri' ,to: 'projects#index'
  match '/search_projects', to: 'projects#search_projects'

  match '/auth/:provider/callback', to: 'users#new'

  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers # ex.: get /users/1/followers
    end
    collection do
      get :search
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :projects do
    collection do
      get :search
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :contributions

  resources :backers

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  attr_accessible :numero, :quota, :servizio, :project_id

  belongs_to :projects
  has_one :project

  default_scope order: 'contributions.quota, contributions.project_id  DESC'

  validates :project_id, presence: true
  validates :numero, :quota, presence: true
  validates :servizio, presence: true, length: {minimum: 5}


end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController

  # check if the user is logged in (e.g., for editing only his information)
  before_filter :signed_in_user, only: [:edit, :update, :index, :destroy]
  # check if the current user is the correct user (e.g., for editing only his information)
  before_filter :correct_user, only: [:edit, :update]


  def new

    @contribution = Contribution.new
    @project = Project.find(params[:project_id])

  end

  def index

    @contributions = Contribution.find_all_by_project_id(params[:project_id])
    @project = Project.find(params[:project_id])
    @bucker= Backer.new

  end

  def update
    if @contribution.update_attributes(params[:contribution])
      # handle a successful update
      flash[:success] = 'Contributo aggiornato!'

      # go to the project
      redirect_to contributions_path(project_id:@project.id)
    else
      # handle a failed update
      render 'edit'
    end
  end



  def edit
    @contribution = Contribution.find_by_id(params[:id])
  end

  def create
    # build a new contribution from the information contained in the "new contribution" form
    @project = Project.find(params[:contribution][:project_id])
    @contribution = @project.contributions.build(params[:contribution])
    if @contribution.save
      flash[:success] = 'Contributo creato!'
      redirect_to contributions_path(project_id:@project.id)

    else
      render 'new'
    end

  end

  def destroy
    contribution = Contribution.find(params[:id])
    project = Project.find_by_id(contribution.project_id)
    contribution.destroy

    redirect_to contributions_path(project_id:project.id)

  end

  private

  def correct_user
    # does the user have a post with the given id?
    @contribution = Contribution.find(params[:id])
    @project = current_user.projects.find_by_id(@contribution.project_id)
    # if not, redirect to the home page
    redirect_to root_url if @project.nil?
  end
end

app/views/contributions/_form.html.erb
<%= form_for(@contribution) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="field">
      <%= f.label :quota, placeholder:'in euro' %><br />
      <%= f.text_field :quota%>


      <%= f.label :servizio %><br />
      <%= f.text_field :servizio %>


      <%= f.label :numero %><br />
      <%= f.number_field :numero, :in => 1..200 %>


      <%= f.hidden_field :project_id, value: @project.id %>

      <div class="actions">
        <%= f.submit 'Crea contributo', class:'btn btn-large btn-success' %>
      </div>
    </div>

<% end %>

app/views/contributions/edit.html.erb
<h1>Modifica contributo</h1>
<div class="span8 offset2">
<%= render 'form' %>
</div>

app/views/contributions/index.html.erb
<h1>Elenco dei contributi</h1>
<div class="row-fluid">
  <div class="span8 offset2">

    <table class="table table-condensed table-bordered table-hover">
      <tr>
        <th>Quota</th>
        <th>Servizio</th>
        <th>Numero</th>
        <th>Azioni</th>
      </tr>

      <% @contributions.each do |contribution| %>
          <tr>
            <td><%= contribution.quota %></td>
            <td><%= contribution.servizio %></td>
            <td><%= contribution.numero %></td>

            <td><%= link_to 'Modifica', edit_contribution_path(contribution.id), class:'btn btn-small btn-primary' %>
              <%= link_to 'Elimina', contribution, method: :delete, id:contribution.id, data: { confirm: 'Sei sicuro?' } ,class:'btn btn-small btn-danger' %>
            </td>
          </tr>
      <% end %>
    </table>

    <br>
    <div class="span2 offset4">
    <%= link_to 'Nuovo Contributo', new_contribution_path(project_id:@project.id),class:'btn btn-large btn-success' %>
    </div>
    <br>
    <br>
    <br>
    <br>
    <%= link_to 'Torna al progetto', @project, class:'btn btn-medium btn-info' %>
  </div>
</div>

app/views/contributions/new.html.erb
<h1>Nuovo contributo</h1>
<div class="row-fluid">
  <div class="span8 offset2">
    <%= render 'form' %>
    <%= link_to 'Torna indietro', contributions_path(project_id: @project.id) %>
  </div>
</div>

app/views/contributions/show.html.erb
<p id="notice"><%= notice %></p>
<div class="span8 offset2">
  <p>
    <b>Quota:</b>
    <%= @contribution.quota %>
  </p>

  <p>
    <b>Servizio:</b>
    <%= @contribution.servizio %>
  </p>

  <p>
    <b>Numero:</b>
    <%= @contribution.numero %>
  </p>


  <%= link_to 'Modifica', edit_contribution_path(@contribution.project_id) %> |
  <%= link_to 'Indietro', contributions_path %>

</div>