config/routes.rb
SWorD::Application.routes.draw do

  root :to => 'pages#home'

  match '/about', to: 'pages#about'
  match '/help', to: 'pages#help'
  match '/faq', to: 'pages#faq'
  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/editproject', to:'projects#edit'
  match '/crea' ,to: 'projects#new'
  match '/scopri' ,to: 'projects#index'
  match '/search_projects', to: 'projects#search_projects'

  match '/auth/:provider/callback', to: 'users#new'

  match '/signout', to: 'sessions#destroy', via: :delete

  resources :users do
    member do
      get :following, :followers # ex.: get /users/1/followers
    end
    collection do
      get :search
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :projects do
    collection do
      get :search
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :contributions

  resources :backers

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://github.com/polito-lam/CrowdFooding" alt="CrowdFooding on GitHub">CrowdFooding</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top ">
  <div class="navbar-inner">
    <div class="container-fluid">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"></a>-->
      <ul class="nav">
        <li><%= image_tag("loghi/ape_logo.png", :size => "45x45") %></li>
        <li><%= link_to "CrowdFooding", root_path, id: "logo" %></li>
      </ul>
      <div class="nav-collapse collapse">
        <nav>
          <ul class="nav pull-center">
            <li><%= image_tag("icone/binoculars2.png", :size => "30x30") %></li>
            <li><%= link_to "Scopri", scopri_path %></li>
            <% if signed_in? %>
                <li><%= image_tag("icone/bulb2.png", :size => "25x25", :options =>
                        {:style=>"padding-top: 10px;"}) %></li>
                <li><%= link_to "Crea", crea_path %></li>
            <% end %>
          </ul>
          <ul class="nav pull-right">
            <% #link_to is the Rails helper to create links (it generates <a...> tags) %>
            <% if signed_in? %>
                <li><%= link_to "Utenti", users_path %></li>
                <li id="fat-menu" class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><%= link_to "Profilo", current_user %></li>
                    <li><%= link_to "Impostazioni", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
                  </ul>
                </li>


            <% else %>
                <li><%=link_to "Sign in", signin_path %></li>
            <% end %>
            <li><%= link_to "About",   about_path %></li>
            <li><%= link_to "Help", help_path %></li>
          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE9]>
<script src="http://htmlshim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <% # method to automatically prevent Cross-Site Request Forgery %>
  <%= csrf_meta_tags %>
  <% # partial for the HTML shim %>
  <%= render 'layouts/shim'%>

  <%= stylesheet_link_tag 'formtastic', 'my_formtastic_changes' %>
  <!--[if IE 6]><%= stylesheet_link_tag 'formtastic_ie6' %><![endif]-->
  <!--[if IE 7]><%= stylesheet_link_tag 'formtastic_ie7' %><![endif]-->
</head>
<body>
<% # partial for the header %>
<%= render 'layouts/header' %>

<div class="container-fluid">
  <% # the flash message; it supports different type of communications %>
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>

  <%= yield %>

  <% # partial for the footer %>
  <%= render 'layouts/footer' %>

  <% # show debug info if development is the actve Rails env %>
  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>